server:
    servlet:
        context-path: /api/v1/
spring:
    application:
        name: updater-installer
    profiles:
        active: dev
    servlet:
        multipart:
            max-file-size: 50MB
springdoc:
    default-produces-media-type: application/json